server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/kun_uz_g2
spring.datasource.username=univer_user
spring.datasource.password=univer_db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.domain.name=http://localhost:${server.port}

attach.url=${server.domain.name}/api/v1/attach

